{% set data = load_setup_py_data() %}

package:
    name: tomosipo
    # If this release is tagged, use bare version number. Otherwise,
    # append 'dev' to version number.
    # This scheme complies with PEP-386:
    # https://www.python.org/dev/peps/pep-0386/
    {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}
    version: {{ data['version'] }}
    {% else %}
    version: {{ data['version'] + "dev" }}
    {% endif %}


source:
    git_url: ../

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    noarch: python

requirements:
    host:
        - python >=3.6
        - astra-toolbox >=2.0
        - setuptools
        - pytest-runner

    run:
        - python >=3.6
        - astra-toolbox >=2.0

about:
    home: https://github.com/ahendriksen/tomosipo
    license: GPL-3.0-only
    license_file: LICENSE
    summary: "Library for painless 3D tomographic reconstruction based on Astra."

extra:
    maintainers:
        - Dirk Schut
        - Allard Hendriksen
